apiVersion: v1
kind: Service
metadata:
  name: zk
  labels:
    app: zk
spec:
  ports:
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: zookeeper
---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata: 
  name: zk
spec: 
  replicas: 3
  serviceName: zk
  template:
    metadata: 
      labels: 
        app: zookeeper
    spec:
      securityContext: 
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: zookeeper
        image: "paulbrown/zookeeper:latest"
        imagePullPolicy: Always
        ports: 
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        env:
        - name : ZK_REPLICAS
          value: "3"
        volumeMounts: 
        - mountPath: /zk_data
          name: data
        - mountPath: /zk_datalog
          name: datalog
        command: 
        - sh
        - -c
        - bin/zkGenConfig.sh && bin/zkServer.sh start-foreground
        readinessProbe:
          exec:
            command:
            - bin/zkOK.sh
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - bin/zkOK.sh
          initialDelaySeconds: 10
          timeoutSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: 
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: standard
  - metadata:
      name: datalog
    spec:
      accessModes: 
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: standard